version: '3.9'

services:

  rapport_engine:
    build:
      context: .
    restart: always
    networks:
      - rapport-engine
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      - rapport-engine
    volumes:
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data:rw
    ports:
      - 127.0.0.1:6379:6379

networks:
  rapport-engine:

volumes:
  redis-data: